name: output meta
on: issues
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v4.1.7
            - name: get info
              run : echo "${{toJson(github)}}" 