name: lint-test-deploy
on: 
  push:
    branches:
      - main
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4.1.7
            - name: cache dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
            - name: install nodejs
              uses: actions/setup-node@v4
            - name: install dependencies
              run: npm ci
            - name: lint
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4.1.7
            - name: install nodejs
              uses: actions/setup-node@v4
            - name: install dependencies
              run: npm ci
            - name: test
              id : run-test
              run: npm run test
            - name: upload artifact
              if: failure() && steps.run-test.outcome == 'failure'
              uses: actions/upload-artifact@v4.4.0
              with:
                name: test-report
                path: |
                  dist
                  test.json
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4.1.7
            - name: install nodejs
              uses: actions/setup-node@v4
            - name: install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: upload artifact
              uses: actions/upload-artifact@v4.4.0
              with:
                name: dist-files
                path: |
                    dist
                    packge.json     
    deploy:
        # needs: build    
        runs-on: ubuntu-latest
        steps:
            - name: download
              uses: actions/download-artifact@v4
              with:
                  name: dist-files
            - name: output contents
              run: ls

    report: 
      needs: [lint, test, deploy, build]
      if: failure()
      runs-on: ubuntu-latest
      steps:
        - name: run this if fails
          run : |
                echo "bla bla bla"
                echo "${{env}}"


      
